export default {
  responses: [
    {
      policy: `<div class="container">
      <p>
        VHP Self Check-in us is committed to protecting your privacy. This
        Privacy Policy explains how your personal information is collected,
        used, and disclosed by VHP Self Check-in.
      </p>
      <p>
        This Privacy Policy applies to (i) the VHP Self Check-in application,
        (ii) our Website and its associated subdomains, and (iii) all services
        provided by our Company in the aforementioned platforms (collectively,
        our “Service”). By accessing or using our Service, you signify that you
        have read, understood, and agree to our collection, storage, use, and
        disclosure of your personal information as described in this Privacy
        Policy and our Terms of Service.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        Definitions and Key Terms
      </h4>
      <p>
        To help explain things as clearly as possible in this Privacy Policy,
        every time any of these terms are referenced, they are strictly defined
        as:
      </p>
      <ul>
        <li>
          Cookie: small amount of data generated by a website and saved by your
          web browser. It is used to identify your browser, provide analytics,
          remember information about you such as your language preference or
          login information.
        </li>
        <li>
          Company: when this policy mentions our “Company", it refers to PT.
          SUPRANUSA SINDATA, (Jl. Bukit Gading Raya, Gading Bukit Indah Blok O
          No. 3-5,Jakarta 14240 - Indonesia) that is responsible for your
          information under this Privacy Policy.
        </li>
        <li>
          Customer: refers to the company, organization or person that signs up
          to use the VHP Self Check-in Service to manage the relationships with
          their consumers or service users.
        </li>
        <li>
          Device: any internet connected device such as a phone, tablet,
          computer or any other device that can be used to visit VHP Self
          Check-in and use the services.
        </li>
        <li>
          IP address: Every device connected to the Internet is assigned a
          number known as an Internet protocol (IP) address. These numbers are
          usually assigned in geographic blocks. An IP address can often be used
          to identify the location from which a device is connecting to the
          Internet.
        </li>
        <li>
          Personnel: refers to those individuals who are employed by VHP Self
          Check-in or are under contract to perform a service on behalf of one
          of the parties.
        </li>
        <li>
          Personal Data: any information that directly, indirectly, or in
          connection with other information — including a personal
          identification number — allows for the identification or
          identifiability of a natural person.
        </li>
        <li>
          Third-party service: refers to advertisers, contest sponsors,
          promotional and marketing partners, and others who provide our content
          or whose products or services we think may interest you.
        </li>
        <li>
          Website: our Company’s site, which can be accessed via this URL:
          https://vhp-online.com
        </li>
        <li>
          You: a person or entity that is registered with VHP Online Check-in to
          use the Services.
        </li>
      </ul>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        What information do we collect?
      </h4>
      <p>
        We collect the following information from you when you use our Service:
      </p>
      <ul>
        <li>Name / Username</li>
        <li>Phone Numbers</li>
        <li>Email Addresses</li>
        <li>Mailing Addresses</li>
        <li>ID card or passport details</li>
      </ul>
      <p>
        We also collect the following information from your mobile devices for a
        better user experience, although these features are completely optional:
      </p>
      <ul>
        <li>
          Photo Gallery (Pictures): Granting photo gallery access allows the
          user to upload any picture from their photo gallery, you can safely
          deny photo gallery access for this website.
        </li>
      </ul>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        How do we use the information we collect?
      </h4>
      <p>
        Any of the information we collect from you may be used in one of the
        following ways:
      </p>
      <ul>
        <li>
          To personalize your experience (your information helps us to better
          respond to your individual needs)
        </li>
        <li>
          To improve our website (we continually strive to improve our website
          offerings based on the information and feedback we receive from you)
        </li>
        <li>
          To improve customer service (your information helps us to more
          effectively respond to your customer service requests and support
          needs)
        </li>
        <li>To process transactions</li>
      </ul>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        When do we use end user information from third parties?
      </h4>
      <p>
        VHP Self Check-in will collect end user data necessary to provide the
        VHP Self Check-in services to our customers.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        When do we use customer information from third parties?
      </h4>
      <p>
        We receive some information from the third parties when you contact us.
        For example, when you submit your email address to us to show interest
        in becoming a VHP Self Check-in customer, we receive information from a
        third party that provides automated fraud detection services to VHP Self
        Check-in. We also occasionally collect information that is made publicly
        available on social media websites.
      </p>
      <p>
        You can control how much of your information social media websites make
        public by visiting these websites and changing your privacy settings.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        Do we share the information we collect with third parties?
      </h4>
      <p>
        We may engage trusted third party service providers to perform functions
        and provide services to us, such as hosting and maintaining our servers
        and the website, database storage and management, e-mail management,
        storage marketing, credit card processing, customer service and
        fulfilling orders for products and services you may purchase through the
        website. We will likely share your personal information, and possibly
        some non-personal information, with these third parties to enable them
        to perform these services for us and for you.
      </p>
      <p>
        We may share portions of our log file data, including IP addresses, for
        analytics purposes with third parties such as web analytics partners,
        application developers, and ad networks. If your IP address is shared,
        it may be used to estimate general location and other technographics
        such as connection speed, whether you have visited the website in a
        shared location, and type of the device used to visit the website. They
        may aggregate information about our advertising and what you see on the
        website and then provide auditing, research and reporting for us and our
        advertisers.
      </p>
      <p>
        We may also disclose personal and non-personal information about you to
        government or law enforcement officials or private parties as we, in our
        sole discretion, believe necessary or appropriate in order to respond to
        claims, legal process (including subpoenas), to protect our rights and
        interests or those of a third party, the safety of the public or any
        person, to prevent or stop any illegal, unethical, or legally actionable
        activity, or to otherwise comply with applicable court orders, laws,
        rules and regulations.
      </p>
      <p>
        Without prejudice to the above, you may request any specific collected
        Personal Data to be treated as confidential.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        Where and when is information collected from customers and end users?
      </h4>
      <p>
        VHP Self Check-in will collect personal information that you submit to
        us. We may also receive personal information about you from third
        parties as described above.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        How Long Do We Keep Your Information?
      </h4>
      <p>
        We keep your information only so long as we need it to provide VHP Self
        Check-in to you and fulfill the purposes described in this policy. This
        is also the case for anyone that we share your information with and who
        carries out services on our behalf. When we no longer need to use your
        information and there is no need for us to keep it to comply with our
        legal or regulatory obligations, we’ll either remove it from our systems
        or depersonalize it so that we can't identify you.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        How Do We Protect Your Information?
      </h4>
      <p>
        We implement a variety of security measures to maintain the safety of
        your personal information when you place an order or enter, submit, or
        access your personal information. We offer the use of a secure server.
        All supplied sensitive/credit information is transmitted via Secure
        Socket Layer (SSL) technology and then encrypted into our Payment
        gateway providers database only to be accessible by those authorized
        with special access rights to such systems, and are required to keep the
        information confidential. After a transaction, your private information
        (credit cards, social security numbers, financials, etc.) is never kept
        on file. We cannot, however, ensure or warrant the absolute security of
        any information you transmit to VHP Self Check-in or guarantee that your
        information on the Service may not be accessed, disclosed, altered, or
        destroyed by a breach of any of our physical, technical, or managerial
        safeguards.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        Could my information be transferred to other countries?
      </h4>
      <p>
        VHP Self Check-in is based in Indonesia. Information collected via our
        application or website, through direct interactions with you, or from
        use of our help services may be transferred from time to time to our
        offices or personnel, or to third parties, located throughout the world,
        and may be viewed and hosted anywhere in the world, including countries
        that may not have laws of general applicability regulating the use and
        transfer of such data. To the fullest extent allowed by applicable law,
        by using any of the above, you voluntarily consent to the trans-border
        transfer and hosting of such information.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        Is the information collected through the VHP Self Check-in Service
        secure?
      </h4>
      <p>
        We take precautions to protect the security of your information. We have
        physical, electronic, and managerial procedures to help safeguard,
        prevent unauthorized access, maintain data security, and correctly use
        your information. However, neither people nor security systems are
        foolproof, including encryption systems. In addition, people can commit
        intentional crimes, make mistakes or fail to follow policies. Therefore,
        while we use reasonable efforts to protect your personal information, we
        cannot guarantee its absolute security. If applicable law imposes any
        non-disclaimable duty to protect your personal information, you agree
        that intentional misconduct will be the standards used to measure our
        compliance with that duty.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        Can I update or correct my information?
      </h4>
      <p>
        The rights you have to request updates or corrections to the information
        VHP Self Check-in collects depend on your relationship with VHP Self
        Check-in. Personnel may update or correct their information as detailed
        in our internal company employment policies.
      </p>
      <p>
        Customers have the right to request the restriction of certain uses and
        disclosures of personally identifiable information as follows. You can
        contact us in order to (1) update or correct your personally
        identifiable information, (2) change your preferences with respect to
        communications and other information you receive from us, or (3) delete
        the personally identifiable information maintained about you on our
        systems (subject to the following paragraph), by cancelling your
        account. Such updates, corrections, changes and deletions will have no
        effect on other information that we maintain, or information that we
        have provided to third parties in accordance with this Privacy Policy
        prior to such update, correction, change or deletion. To protect your
        privacy and security, we may take reasonable steps (such as requesting a
        unique password) to verify your identity before granting you profile
        access or making corrections. You are responsible for maintaining the
        secrecy of your unique password and account information at all times.
      </p>
      <p>
        You should be aware that it is not technologically possible to remove
        each and every record of the information you have provided to us from
        our system. The need to back up our systems to protect information from
        inadvertent loss means that a copy of your information may exist in a
        non-erasable form that will be difficult or impossible for us to locate.
        Promptly after receiving your request, all personal information stored
        in databases we actively use, and other readily searchable media will be
        updated, corrected, changed or deleted, as appropriate, as soon as and
        to the extent reasonably and technically practicable.
      </p>
      <p>
        If you are an end user and wish to update, delete, or receive any
        information we have about you, you may do so by contacting the
        organization of which you are a customer.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        Personnel
      </h4>
      <p>
        If you are a VHP Online Check-in worker or applicant, we collect
        information you voluntarily provide to us. We use the information
        collected for Human Resources purposes in order to administer benefits
        to workers and screen applicants.
      </p>
      <p>
        You may contact us in order to (1) update or correct your information,
        (2) change your preferences with respect to communications and other
        information you receive from us, or (3) receive a record of the
        information we have relating to you. Such updates, corrections, changes
        and deletions will have no effect on other information that we maintain,
        or information that we have provided to third parties in accordance with
        this Privacy Policy prior to such update, correction, change or
        deletion.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        Sale of Business
      </h4>
      <p>
        We reserve the right to transfer information to a third party in the
        event of a sale, merger or other transfer of all or substantially all of
        the assets of VHP Self Check-in or any of its Corporate Affiliates (as
        defined herein), or that portion of VHP Self Check-in or any of its
        Corporate Affiliates to which the Service relates, or in the event that
        we discontinue our business or file a petition or have filed against us
        a petition in bankruptcy, reorganization or similar proceeding, provided
        that the third party agrees to adhere to the terms of this Privacy
        Policy.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        Affiliates
      </h4>
      <p>
        We may disclose information (including personal information) about you
        to our Corporate Affiliates. For purposes of this Privacy Policy,
        "Corporate Affiliate" means any person or entity which directly or
        indirectly controls, is controlled by or is under common control with
        VHP Online Check-in, whether by ownership or otherwise. Any information
        relating to you that we provide to our Corporate Affiliates will be
        treated by those Corporate Affiliates in accordance with the terms of
        this Privacy Policy.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        Governing Law
      </h4>
      <p>
        This Privacy Policy is governed by the laws of Indonesia without regard
        to its conflict of laws provision. You consent to the exclusive
        jurisdiction of the Indonesian courts in connection with any action or
        dispute arising between the parties under or in connection with this
        Privacy Policy except for those individuals who may have rights to make
        claims under Privacy Shield, or the Swiss-US framework.
      </p>
      <p>
        The laws of Indonesia, excluding its conflicts of law rules, shall
        govern this Privacy Policy and your use of our Service. Your use of the
        website may also be subject to other local, state, national, or
        international laws.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        Your Consent
      </h4>
      <p>
        By accessing our platforms or using our Service, you signify your
        acceptance of this Privacy Policy. If you do not agree to this Privacy
        Policy, you should not engage with our platforms or use our Service.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        Links to Other Websites
      </h4>
      <p>
        This Privacy Policy applies only to the Services. The Services may
        contain links to other websites not operated or controlled by VHP Self
        Check-in. We are not responsible for the content, accuracy or opinions
        expressed in such websites, and such websites are not investigated,
        monitored or checked for accuracy or completeness by us. Please remember
        that when you use a link to go from the Services to another website, our
        Privacy Policy is no longer in effect. Your browsing and interaction on
        any other website, including those that have a link on our platform, is
        subject to that website’s own rules and policies. Such third parties may
        use their own cookies or other methods to collect information about you.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        Cookies
      </h4>
      <p>
        VHP Self Check-in uses "Cookies" to identify the areas of our website
        that you have visited. A Cookie is a small piece of data stored on your
        computer or mobile device by your web browser. We use Cookies to enhance
        the performance and functionality of our website but are non-essential
        to their use. However, without these cookies, certain functionality like
        videos may become unavailable or you would be required to enter your
        login details every time you visit the website as we would not be able
        to remember that you had logged in previously. Most web browsers can be
        set to disable the use of Cookies. However, if you disable Cookies, you
        may not be able to access functionality on our website correctly or at
        all. We never place Personally Identifiable Information in Cookies.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        Blocking and disabling cookies and similar technologies
      </h4>
      <p>
        Wherever you're located you may also set your browser to block cookies
        and similar technologies, but this action may block our essential
        cookies and prevent our website from functioning properly, and you may
        not be able to fully utilize all of its features and services. You
        should also be aware that you may also lose some saved information (e.g.
        saved login details, site preferences) if you block cookies on your
        browser. Different browsers make different controls available to you.
        Disabling a cookie or category of cookie does not delete the cookie from
        your browser, you will need to do this yourself from within your
        browser, you should visit your browser's help menu for more information.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        Payment Details
      </h4>
      <p>
        In respect to any credit card or other payment processing details you
        have provided us, we commit that this confidential information will be
        stored in the most secure manner possible.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        Kids' Privacy
      </h4>
      <p>
        We do not address anyone under the applicable legal age in their
        respective jurisdiction. We do not knowingly collect personally
        identifiable information from anyone under the applicable legal age. If
        You are a parent or guardian and You are aware that Your child has
        provided Us with Personal Data, please contact Us. If We become aware
        that We have collected Personal Data from anyone under the legal age
        without verification of parental consent, We will take steps to remove
        that information from Our servers.
      </p>
      <p>
        By providing your consent to this Privacy Policy, you declare that you
        are of the legal age in your jurisdiction and have the full authority to
        make the consent.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        Changes To Our Privacy Policy
      </h4>
      <p>
        We may change our Service and policies from time to time, and we may
        need to make changes to this Privacy Policy so that they accurately
        reflect our Service and policies. Unless otherwise required by law, we
        will notify you (for example, through our Service) immediately after we
        make changes to this Privacy Policy to give you an opportunity to review
        them. Your continued use of our Service signifies your acceptance of the
        changes to this Privacy Policy and your agreement to be bound by the
        updated Privacy Policy. If you do not agree to this or any updated
        Privacy Policy, you should not engage with our platforms or use our
        Service further.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        Third-Party Services
      </h4>
      <p>
        We may display, include or make available third-party content (including
        data, information, applications and other products services) or provide
        links to third-party websites or services ("Third- Party Services").
      </p>
      <p>
        You acknowledge and agree that VHP Self Check-in shall not be
        responsible for any Third-Party Services, including their accuracy,
        completeness, timeliness, validity, copyright compliance, legality,
        decency, quality or any other aspect thereof. VHP Online Check-in does
        not assume and shall not have any liability or responsibility to you or
        any other person or entity for any Third-Party Services.
      </p>
      <p>
        Third-Party Services and links thereto are provided solely as a
        convenience to you and you access and use them entirely at your own risk
        and subject to such third parties' terms and conditions.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        Tracking Technologies
      </h4>
      <p>
        <b><b>Cookies</b></b>
      </p>
      <p>
        We use Cookies to enhance the performance and functionality of our
        website but are non-essential to their use. However, without these
        cookies, certain functionality like videos may become unavailable or you
        would be required to enter your login details every time you visit the
        website as we would not be able to remember that you had logged in
        previously.
      </p>
      <p>
        <b><b>Local Storage</b></b>
      </p>
      <p>
        Local Storage sometimes known as DOM storage, provides web apps with
        methods and protocols for storing client-side data. Web storage supports
        persistent data storage, similar to cookies but with a greatly enhanced
        capacity and no information stored in the HTTP request header.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        Information about General Data Protection Regulation (GDPR)
      </h4>
      <p>
        We may be collecting and using information from you if you are from the
        European Economic Area (EEA), and in this section of our Privacy Policy
        we are going to explain exactly how and why is this data collected, and
        how we maintain this data under protection from being replicated or used
        in the wrong way.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        What is GDPR?
      </h4>
      <p>
        GDPR is an EU-wide privacy and data protection law that regulates how EU
        residents' data is protected by companies and enhances the control the
        EU residents have, over their personal data.
      </p>
      <p>
        The GDPR is relevant to any globally operating company and not just the
        EU-based businesses and EU residents. Our customers’ data is important
        irrespective of where they are located, which is why we have implemented
        GDPR controls as our baseline standard for all our operations worldwide.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        What is personal data?
      </h4>
      <p>
        Any data that relates to an identifiable or identified individual. GDPR
        covers a broad spectrum of information that could be used on its own, or
        in combination with other pieces of information, to identify a person.
        Personal data extends beyond a person’s name or email address. Some
        examples include financial information, political opinions, genetic
        data, biometric data, IP addresses, physical address, sexual
        orientation, and ethnicity.
      </p>
      <p><b>The Data Protection Principles include requirements such as:</b></p>
      <ul>
        <li>
          Personal data collected must be processed in a fair, legal, and
          transparent way and should only be used in a way that a person would
          reasonably expect.
        </li>
        <li>
          Personal data should only be collected to fulfil a specific purpose
          and it should only be used for that purpose. Organizations must
          specify why they need the personal data when they collect it.
        </li>
        <li>
          Personal data should be held no longer than necessary to fulfil its
          purpose.
        </li>
        <li>
          People covered by the GDPR have the right to access their own personal
          data. They can also request a copy of their data, and that their data
          be updated, deleted, restricted, or moved to another organization.
        </li>
      </ul>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        Why is GDPR important?
      </h4>
      <p>
        GDPR adds some new requirements regarding how companies should protect
        individuals' personal data that they collect and process. It also raises
        the stakes for compliance by increasing enforcement and imposing greater
        fines for breach. Beyond these facts it's simply the right thing to do.
        At Help Scout we strongly believe that your data privacy is very
        important and we already have solid security and privacy practices in
        place that go beyond the requirements of this new regulation.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        Individual Data Subject's Rights - Data Access, Portability and Deletion
      </h4>
      <p>
        We are committed to helping our customers meet the data subject rights
        requirements of GDPR. VHP Self Check-in processes or stores all personal
        data in fully vetted, DPA compliant vendors. We do store all
        conversation and personal data for up to 6 years unless your account is
        deleted. In which case, we dispose of all data in accordance with our
        Terms of Service and Privacy Policy, but we will not hold it longer than
        60 days.
      </p>
      <p>
        We are aware that if you are working with EU customers, you need to be
        able to provide them with the ability to access, update, retrieve and
        remove personal data. We got you! We've been set up as self service from
        the start and have always given you access to your data and your
        customers data. Our customer support team is here for you to answer any
        questions you might have about working with the API.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        Contact Us
      </h4>
      <p>Don't hesitate to contact us if you have any questions.</p>
      <ul>
        <li>Email: <a href="mailto:info@sindata.net">info@sindata.net</a></li>
        <li>Phone Number: (62) 21 - 50860678</li>
        <li>
          Website:
          <a href="https://www.sindata.net">https://www.sindata.net</a>
        </li>
        <li>
          Address: Jl. Bukit Gading Raya, Gading Bukit Indah Blok O No. 3-5,
          Jakarta 14240 - Indonesia
        </li>
      </ul>
    </div>`,

      policeTrans: `<div class="container">
      <p>
        VHP Self Check-in kami berkomitmen untuk melindungi privasi Anda.
        Kebijakan Privasi ini menjelaskan bagaimana informasi pribadi Anda
        dikumpulkan, digunakan, dan diungkapkan oleh VHP Self Check-in.
      </p>
      <p>
        Kebijakan Privasi ini berlaku untuk situs (i) aplikasi VHP Self
        Check-in, (ii) Situs Web kami beserta subdomain terkait, dan (iii)
        segala Layanan yang diberikan oleh Perusahaan kami pada
        platform-platform yang disebutkan sebelum ini (secara kolektif,
        "Layanan"). Dengan mengakses atau menggunakan Layanan kami, Anda
        menandakan bahwa Anda telah membaca, memahami, dan menyetujui
        pengumpulan, penyimpanan, penggunaan, dan pengungkapan informasi pribadi
        Anda sebagaimana dijelaskan dalam Kebijakan Privasi ini dan Ketentuan
        Layanan kami.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        Definisi dan istilah kunci
      </h4>
      <p>
        Untuk membantu menjelaskan hal-hal sejelas mungkin dalam Kebijakan
        Privasi ini, setiap kali salah satu istilah ini dirujuk, didefinisikan
        secara ketat sebagai:
      </p>
      <ul>
        <li>
          Cookie: sejumlah kecil data yang dihasilkan oleh situs web dan
          disimpan oleh browser web Anda. Ini digunakan untuk mengidentifikasi
          browser Anda, menyediakan analitik, mengingat informasi tentang Anda
          seperti preferensi bahasa atau informasi login Anda.
        </li>
        <li>
          Perusahaan: ketika kebijakan ini menyebutkan "Perusahaan" kami, itu
          mengacu pada PT. SUPRANUSA SINDATA, (Jl. Bukit Gading Raya, Gading
          Bukit Indah Blok O No. 3-5,Jakarta 14240 - Indonesia) yang bertanggung
          jawab atas informasi Anda berdasarkan Kebijakan Privasi ini.
        </li>
        <li>
          Pelanggan: mengacu pada perusahaan, organisasi, atau orang yang
          mendaftar untuk menggunakan Layanan Check-in Mandiri VHP untuk
          mengelola hubungan dengan konsumen atau pengguna layanan Anda.
        </li>
        <li>
          Perangkat: perangkat apa pun yang terhubung ke internet seperti
          ponsel, tablet, komputer, atau perangkat lain yang dapat digunakan
          untuk mengunjungi VHP Self Check-in dan menggunakan layanan.
        </li>
        <li>
          Alamat IP: Setiap perangkat yang terhubung ke Internet diberi nomor
          yang dikenal sebagai alamat protokol Internet (IP). Angka-angka ini
          biasanya ditetapkan dalam blok geografis. Alamat IP sering dapat
          digunakan untuk mengidentifikasi lokasi tempat perangkat terhubung ke
          Internet.
        </li>
        <li>
          Personil: mengacu pada orang-orang yang dipekerjakan oleh VHP Self
          Check-in atau berada di bawah kontrak untuk melakukan layanan atas
          nama salah satu pihak.
        </li>
        <li>
          Data Pribadi: setiap informasi yang secara langsung, tidak langsung,
          atau sehubungan dengan informasi lain - termasuk nomor identifikasi
          pribadi - memungkinkan untuk identifikasi atau identifikasi orang
          alami.
        </li>
        <li>
          Layanan pihak ketiga: mengacu pada pengiklan, sponsor kontes, mitra
          promosi dan pemasaran, dan lainnya yang menyediakan konten kami atau
          yang produk atau layanannya menurut kami mungkin menarik bagi Anda.
        </li>
        <li>
          Situs Web: situs milik Perusahaan kami, yang dapat diakses melalui URL
          ini: https://vhp-online.com
        </li>
        <li>
          Anda: seseorang atau entitas yang terdaftar di VHP Online Check-in
          untuk menggunakan Layanan.
        </li>
      </ul>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        Informasi Apa yang Kami Kumpulkan?
      </h4>
      <p>
        Kami mengumpulkan informasi berikut ini dari Anda ketika Anda
        menggunakan Jasa kami:
      </p>
      <ul>
        <li>Nama / Nama user</li>
        <li>Nomor Telepon</li>
        <li>Alamat Email</li>
        <li>Alamat Surat</li>
        <li>Rincian Kartu Tanda Penduduk atau paspor</li>
      </ul>
      <p>
        Kami juga mengumpulkan informasi berikut ini dari perangkat seluler Anda
        untuk pengalaman pengguna yang lebih baik, meskipun fitur-fitur ini
        sepenuhnya opsional:
      </p>
      <ul>
        <li>
          Photo Gallery (Gambar): Memberikan akses galeri foto memungkinkan
          pengguna untuk mengunggah gambar apa pun dari galeri foto mereka, Anda
          dapat dengan aman menolak akses galeri foto untuk situs web ini.
        </li>
      </ul>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        Bagaimana kami menggunakan informasi yang kami kumpulkan?
      </h4>
      <p>
        Salah satu informasi yang kami kumpulkan dari Anda dapat digunakan
        dengan salah satu cara berikut:
      </p>
      <ul>
        <li>
          Untuk mempersonalisasi pengalaman Anda (informasi Anda membantu kami
          merespons kebutuhan individu Anda dengan lebih baik)
        </li>
        <li>
          Untuk meningkatkan situs web kami (kami terus berusaha untuk
          meningkatkan penawaran situs web kami berdasarkan informasi dan umpan
          balik yang kami terima dari Anda)
        </li>
        <li>
          Untuk meningkatkan layanan pelanggan (informasi Anda membantu kami
          untuk lebih efektif menanggapi permintaan layanan pelanggan dan
          kebutuhan dukungan Anda)
        </li>
        <li>Untuk memproses transaksi</li>
      </ul>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        Kapan VHP Self Check-in menggunakan informasi pengguna akhir dari pihak
        ketiga?
      </h4>
      <p>
        VHPSelf Check-in akan mengumpulkan Data Pengguna Akhir yang diperlukan
        untuk menyediakan layanan Check-in Mandiri VHP kepada pelanggan kami.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        Kapan VHP Self Check-in menggunakan informasi pelanggan dari pihak
        ketiga?
      </h4>
      <p>
        Kami dapat melibatkan penyedia layanan pihak ketiga tepercaya untuk
        melakukan fungsi dan menyediakan layanan kepada kami, seperti
        menghosting dan memelihara server kami dan situs web, penyimpanan dan
        manajemen database, manajemen email, pemasaran penyimpanan, pemrosesan
        kartu kredit, layanan pelanggan dan memenuhi pesanan untuk produk dan
        layanan yang dapat Anda beli melalui situs web. Kami kemungkinan akan
        membagikan informasi pribadi Anda, dan mungkin beberapa informasi
        non-pribadi, dengan pihak ketiga ini untuk memungkinkan mereka melakukan
        layanan ini untuk kami dan untuk Anda.
      </p>
      <p>
        Kami dapat membagikan sebagian data file log kami, termasuk alamat IP,
        untuk tujuan analitik dengan pihak ketiga seperti mitra analitik web,
        pengembang aplikasi, dan jaringan iklan. Jika alamat IP Anda dibagikan,
        alamat IP Anda dapat digunakan untuk memperkirakan lokasi umum dan
        teknografi lain seperti kecepatan koneksi, apakah Anda telah mengunjungi
        situs web di lokasi bersama, dan jenis perangkat yang digunakan untuk
        mengunjungi situs web. Mereka dapat mengumpulkan informasi tentang iklan
        kami dan apa yang Anda lihat di situs web dan kemudian memberikan audit,
        penelitian, dan pelaporan untuk kami dan pengiklan kami.
      </p>
      <p>
        Kami juga dapat mengungkapkan informasi pribadi dan non-pribadi tentang
        Anda kepada pemerintah atau aparat penegak hukum atau pihak swasta
        sebagai kami, atas kebijakan kami sendiri, percaya perlu atau tepat
        untuk menanggapi klaim, proses hukum (termasuk panggilan pengadilan),
        untuk melindungi hak dan kepentingan kami atau orang-orang dari pihak
        ketiga, keselamatan publik atau siapa pun, untuk mencegah atau
        menghentikan aktivitas ilegal, tidak etis, atau dapat ditinarakan secara
        hukum, atau untuk mematuhi perintah pengadilan, hukum, aturan, dan
        peraturan yang berlaku.
      </p>
      <p>
        Tanpa mengesampingkan ketentuan di atas, Anda dapat meminta agar Data
        Pribadi tertentu yang kami kumpulkan diberlakukan sebagai rahasia.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        Di mana dan kapan informasi dikumpulkan dari pelanggan dan pengguna
        akhir?
      </h4>
      <p>
        VHP Self Check-in akan mengumpulkan informasi pribadi yang Anda kirimkan
        kepada kami. Kami juga dapat menerima informasi pribadi tentang Anda
        dari pihak ketiga seperti yang dijelaskan di atas.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        Berapa lama kami menyimpan informasi Anda?
      </h4>
      <p>
        Kami menyimpan informasi Anda hanya selama kami membutuhkannya untuk
        memberikan VHP Self Check-in kepada Anda dan memenuhi tujuan yang
        dijelaskan dalam kebijakan ini. Ini juga terjadi bagi siapa pun yang
        kami bagikan informasi Anda dengan dan yang melakukan layanan atas nama
        kami. Ketika kami tidak perlu lagi menggunakan informasi Anda dan tidak
        perlu bagi kami untuk menyimpannya untuk mematuhi kewajiban hukum atau
        peraturan kami, kami akan menghapusnya dari sistem kami atau
        mendepersonalisasikannya sehingga kami tidak dapat mengidentifikasi
        Anda.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        Bagaimana Kami Melindungi Informasi Anda?
      </h4>
      <p>
        Kami menerapkan berbagai langkah keamanan untuk menjaga keamanan
        informasi pribadi Anda saat Anda melakukan pemesanan atau memasukkan,
        mengirimkan, atau mengakses informasi pribadi Anda. Kami menawarkan
        penggunaan server yang aman. Semua informasi sensitif / kredit yang
        disediakan dikirimkan melalui teknologi Secure Socket Layer (SSL) dan
        kemudian dienkripsi ke dalam database penyedia gateway Pembayaran kami
        hanya untuk dapat diakses oleh mereka yang berwenang dengan hak akses
        khusus untuk sistem tersebut, dan diharuskan untuk menjaga kerahasiaan
        informasi. Setelah transaksi, informasi pribadi Anda (kartu kredit,
        nomor jaminan sosial, keuangan, dll.) tidak pernah disimpan di file.
        Namun, kami tidak dapat memastikan atau menjamin keamanan mutlak dari
        informasi apa pun yang Anda kirimkan ke VHP Self Check-in atau menjamin
        bahwa informasi Anda tentang Layanan tidak dapat diakses, diungkapkan,
        diubah, atau dihancurkan oleh pelanggaran perlindungan fisik, teknis,
        atau manajerial kami.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        Mungkinkah informasi saya ditransfer ke negara lain?
      </h4>
      <p>
        VHP Self Check-in memiliki pusat operasi di Indonesia. Informasi yang
        dikumpulkan melalui aplikasi atau situs web kami, melalui interaksi
        langsung dengan Anda, atau dari penggunaan layanan bantuan kami dapat
        ditransfer dari waktu ke waktu ke kantor atau personel kami, atau kepada
        pihak ketiga, yang terletak di seluruh dunia, dan dapat dilihat dan
        dihosting di mana saja di dunia, termasuk negara-negara yang mungkin
        tidak memiliki undang-undang penerapan umum yang mengatur penggunaan dan
        transfer data tersebut. Sejauh diizinkan oleh hukum yang berlaku, dengan
        menggunakan salah satu hal di atas, Anda secara sukarela menyetujui
        transfer trans-perbatasan dan hosting informasi tersebut.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        Apakah informasi yang dikumpulkan melalui Layanan Check-in Mandiri VHP
        aman?
      </h4>
      <p>
        Kami mengambil tindakan pencegahan untuk melindungi keamanan informasi
        Anda. Kami memiliki prosedur fisik, elektronik, dan manajerial untuk
        membantu melindungi, mencegah akses tidak sah, menjaga keamanan data,
        dan menggunakan informasi Anda dengan benar. Namun, baik orang maupun
        sistem keamanan tidak mudah dibodohi, termasuk sistem enkripsi. Selain
        itu, masyarakat dapat melakukan kejahatan yang disengaja, melakukan
        kesalahan atau gagal mengikuti kebijakan. Oleh karena itu, meskipun kami
        menggunakan upaya yang wajar untuk melindungi informasi pribadi Anda,
        kami tidak dapat menjamin keamanan mutlaknya. Jika hukum yang berlaku
        memberlakukan tugas yang tidak dapat disanggah untuk melindungi
        informasi pribadi Anda, Anda setuju bahwa pelanggaran yang disengaja
        akan menjadi standar yang digunakan untuk mengukur kepatuhan kami
        terhadap tugas tersebut.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        Bisakah saya memperbarui atau memperbaiki informasi saya?
      </h4>
      <p>
        Hak yang Anda miliki untuk meminta pembaruan atau koreksi pada informasi
        yang dikumpulkan VHP Self Check-in tergantung pada hubungan Anda dengan
        VHP Self Check-in. Personil dapat memperbarui atau memperbaiki informasi
        mereka sebagaimana dirinci dalam kebijakan ketenagakerjaan internal
        perusahaan kami.
      </p>
      <p>
        Pelanggan berhak untuk meminta pembatasan penggunaan dan pengungkapan
        informasi identitas pribadi sebagai berikut. Anda dapat menghubungi kami
        untuk (1) memperbarui atau memperbaiki informasi identitas pribadi Anda,
        (2) mengubah preferensi Anda sehubungan dengan komunikasi dan informasi
        lain yang Anda terima dari kami, atau (3) menghapus informasi identitas
        pribadi yang dikelola tentang Anda di sistem kami (tunduk pada paragraf
        berikut), dengan membatalkan akun Anda. Pembaruan, koreksi, perubahan,
        dan penghapusan tersebut tidak akan berpengaruh pada informasi lain yang
        kami pertahankan, atau informasi yang telah kami berikan kepada pihak
        ketiga sesuai dengan Kebijakan Privasi ini sebelum pembaruan, koreksi,
        perubahan, atau penghapusan tersebut. Untuk melindungi privasi dan
        keamanan Anda, kami dapat mengambil langkah-langkah yang wajar (seperti
        meminta kata sandi unik) untuk memverifikasi identitas Anda sebelum
        memberi Anda akses profil atau melakukan koreksi. Anda bertanggung jawab
        untuk menjaga kerahasiaan kata sandi unik dan informasi akun Anda setiap
        saat.
      </p>
      <p>
        Anda harus menyadari bahwa tidak mungkin secara teknologi untuk
        menghapus masing-masing dan setiap catatan informasi yang telah Anda
        berikan kepada kami dari sistem kami. Kebutuhan untuk mencadangkan
        sistem kami untuk melindungi informasi dari kehilangan yang tidak
        disengaja berarti bahwa salinan informasi Anda mungkin ada dalam bentuk
        yang tidak dapat di-penghapusan yang akan sulit atau tidak mungkin bagi
        kami untuk menemukan. Segera setelah menerima permintaan Anda, semua
        informasi pribadi yang disimpan dalam database yang kami gunakan secara
        aktif, dan media lain yang mudah dicari akan diperbarui, diperbaiki,
        diubah atau dihapus, sebagaimana mestinya, segera setelah dan sejauh
        yang wajar dan dapat dilakukan secara teknis.
      </p>
      <p>
        Jika Anda adalah pengguna akhir dan ingin memperbarui, menghapus, atau
        menerima informasi apa pun yang kami miliki tentang Anda, Anda dapat
        melakukannya dengan menghubungi organisasi tempat Anda menjadi
        pelanggan.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        Personil
      </h4>
      <p>
        Jika Anda adalah pekerja VHP Online Check-in atau pemohon, kami
        mengumpulkan informasi yang Anda berikan secara sukarela kepada kami.
        Kami menggunakan informasi yang dikumpulkan untuk tujuan Sumber Daya
        Manusia untuk memberikan manfaat kepada pekerja dan pelamar layar.
      </p>
      <p>
        Anda dapat menghubungi kami untuk (1) memperbarui atau memperbaiki
        informasi Anda, (2) mengubah preferensi Anda sehubungan dengan
        komunikasi dan informasi lain yang Anda terima dari kami, atau (3)
        menerima catatan informasi yang kami miliki terkait dengan Anda.
        Pembaruan, koreksi, perubahan, dan penghapusan tersebut tidak akan
        berpengaruh pada informasi lain yang kami pertahankan, atau informasi
        yang telah kami berikan kepada pihak ketiga sesuai dengan Kebijakan
        Privasi ini sebelum pembaruan, koreksi, perubahan, atau penghapusan
        tersebut.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        Penjualan Bisnis
      </h4>
      <p>
        Kami berhak untuk mentransfer informasi kepada pihak ketiga jika terjadi
        penjualan, penggabungan, atau pengalihan lainnya dari semua atau secara
        substansial semua aset VHP Self Check-in atau Afiliasi Perusahaannya
        (sebagaimana didefinisikan di sini), atau bagian dari VHP Self Check-in
        atau afiliasi Perusahaan mana pun yang terkait dengan Layanan, atau jika
        kami menghentikan bisnis kami atau mengajukan petisi atau telah
        mengajukan petisi kepada kami kebangkrutan, reorganisasi, atau proses
        serupa, asalkan pihak ketiga setuju untuk mematuhi ketentuan Kebijakan
        Privasi ini.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        Afiliasi
      </h4>
      <p>
        Kami dapat mengungkapkan informasi (termasuk informasi pribadi) tentang
        Anda kepada Afiliasi Perusahaan kami. Untuk tujuan Kebijakan Privasi
        ini, "Afiliasi Perusahaan" berarti setiap orang atau entitas yang secara
        langsung atau tidak langsung mengontrol, dikendalikan oleh atau berada
        di bawah kendali bersama dengan VHP Online Check-in, baik dengan
        kepemilikan atau sebaliknya. Setiap informasi yang berkaitan dengan Anda
        yang kami berikan kepada Afiliasi Perusahaan kami akan diperlakukan oleh
        Afiliasi Perusahaan tersebut sesuai dengan ketentuan Kebijakan Privasi
        ini.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        Hukum Yang Mengatur
      </h4>
      <p>
        Kebijakan Privasi ini diatur oleh hukum Indonesia tanpa memperhatikan
        konflik ketentuan hukumnya. Anda menyetujui yurisdiksi eksklusif
        pengadilan Indonesia sehubungan dengan tindakan atau perselisihan apa
        pun yang timbul antara para pihak di bawah atau sehubungan dengan
        Kebijakan Privasi ini kecuali bagi orang-orang yang mungkin memiliki hak
        untuk membuat klaim berdasarkan Perlindungan Privasi, atau kerangka
        kerja Swiss-AS.
      </p>
      <p>
        Hukum Indonesia, tidak termasuk konflik aturan hukumnya, akan mengatur
        Kebijakan Privasi ini dan penggunaan Anda atas Layanan kami. Penggunaan
        Anda atas situs web juga dapat tunduk pada hukum lokal, negara bagian,
        nasional, atau internasional lainnya.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        Persetujuan Anda
      </h4>
      <p>
        Dengan mengakses platform kami atau menggunakan Layanan kami, Anda
        menandakan penerimaan Anda atas Kebijakan Privasi ini. Jika Anda tidak
        menyetujui Kebijakan Privasi ini, Anda tidak disarankan untuk mengakses
        platform kami atau menggunakan layanan kami.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        Tautan ke Situs Web Lain
      </h4>
      <p>
        Kebijakan Privasi ini hanya berlaku untuk Layanan. Layanan mungkin
        berisi tautan ke situs web lain yang tidak dioperasikan atau
        dikendalikan oleh VHP Self Check-in. Kami tidak bertanggung jawab atas
        konten, keakuratan, atau pendapat yang dinyatakan dalam situs web
        tersebut, dan situs web tersebut tidak diselidiki, dipantau, atau
        diperiksa keakuratan atau kelengkapannya oleh kami. Harap diingat bahwa
        ketika Anda menggunakan tautan untuk pergi dari Layanan ke situs web
        lain, Kebijakan Privasi kami tidak lagi berlaku. Penjelajahan dan
        interaksi Anda di situs web lain, termasuk yang memiliki tautan di
        platform kami, tunduk pada aturan dan kebijakan situs web itu sendiri.
        Pihak ketiga tersebut dapat menggunakan cookie mereka sendiri atau
        metode lain untuk mengumpulkan informasi tentang Anda.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        Cookie
      </h4>
      <p>
        VHP Self Check-in menggunakan "Cookie" untuk mengidentifikasi area situs
        web kami yang telah Anda kunjungi. Cookie adalah bagian kecil dari data
        yang disimpan di komputer atau perangkat seluler Anda oleh browser web
        Anda. Kami menggunakan Cookie untuk meningkatkan kinerja dan
        fungsionalitas situs web kami tetapi tidak penting untuk penggunaannya.
        Namun, tanpa cookie ini, fungsi tertentu seperti video mungkin menjadi
        tidak tersedia atau Anda akan diminta untuk memasukkan detail login Anda
        setiap kali Anda mengunjungi situs web karena kami tidak akan dapat
        mengingat bahwa Anda telah masuk sebelumnya. Sebagian besar browser web
        dapat diatur untuk menonaktifkan penggunaan Cookie. Namun, jika Anda
        menonaktifkan Cookie, Anda mungkin tidak dapat mengakses fungsionalitas
        di situs web kami dengan benar atau sama sekali. Kami tidak pernah
        menempatkan Informasi Identitas Pribadi di Cookie.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        Memblokir dan menonaktifkan cookie dan teknologi serupa
      </h4>
      <p>
        Di mana pun Anda berada, Anda juga dapat mengatur browser Anda untuk
        memblokir cookie dan teknologi serupa, tetapi tindakan ini dapat
        memblokir cookie penting kami dan mencegah situs web kami berfungsi
        dengan baik, dan Anda mungkin tidak dapat sepenuhnya menggunakan semua
        fitur dan layanannya. Anda juga harus menyadari bahwa Anda mungkin juga
        kehilangan beberapa informasi yang disimpan (misalnya detail login
        tersimpan, preferensi situs) jika Anda memblokir cookie di browser Anda.
        Browser yang berbeda membuat kontrol yang berbeda tersedia untuk Anda.
        Menonaktifkan cookie atau kategori cookie tidak menghapus cookie dari
        browser Anda, Anda harus melakukan ini sendiri dari dalam browser Anda,
        Anda harus mengunjungi menu bantuan browser Anda untuk informasi lebih
        lanjut.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        Detail Pembayaran
      </h4>
      <p>
        Sehubungan dengan kartu kredit atau detail pemrosesan pembayaran lainnya
        yang telah Anda berikan kepada kami, kami berkomitmen bahwa informasi
        rahasia ini akan disimpan dengan cara yang paling aman.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        Privasi Anak-Anak
      </h4>
      <p>
        Kami tidak melayani siapa pun di bawah usia dewasa yang berlaku pada
        yurisdiksi yang relevan. Kami tidak secara sadar mengumpulkan informasi
        identitas pribadi dari siapa pun di bawah usia dewasa. Jika Anda adalah
        orang tua atau wali dan Anda menyadari bahwa anak Anda telah memberi
        Kami Data Pribadi, silakan hubungi Kami. Jika Kami mengetahui bahwa Kami
        telah mengumpulkan Data Pribadi dari siapa pun yang berusia di bawah
        usia dewasa tanpa verifikasi persetujuan orang tua, Kami akan mengambil
        langkah-langkah untuk menghapus informasi tersebut dari server Kami.
      </p>
      <p>
        Dengan memberikan persetujuan Anda atas Kebijakan Privasi ini, Anda
        menyatakan bahwa Anda telah berusia dewasa menurut ketentuan yurisdiksi
        Anda dan memiliki wewenang penuh untuk memberikan persetujuan tersebut.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        Perubahan kebijakan privasi kami
      </h4>
      <p>
        Kami dapat mengubah Layanan dan kebijakan kami dari waktu ke waktu, dan
        kami mungkin perlu membuat perubahan pada Kebijakan Privasi ini sehingga
        secara akurat mencerminkan Layanan dan kebijakan kami. Kecuali
        diwajibkan lain oleh hukum, kami akan memberi tahu Anda (misalnya,
        melalui Layanan kami) segera setelah kami membuat perubahan pada
        Kebijakan Privasi ini untuk memberi Anda kesempatan untuk meninjaunya.
        Pengunaan secara terus menerus oleh Anda atas Layanan menandakan
        penerimaan Anda atas perubahan-perubahan pada Kebijakan Privasi ini dan
        persetujuan Anda untuk terikat oleh Kebijakan Privasi yang diperbarui.
        Jika Anda tidak ingin menyetujui kebijakan privasi ini atau yang
        diperbarui, Anda tidak disarankan untuk mengakses platform kami atau
        menggunakan layanan kami lebih lanjut.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        Layanan Pihak Ketiga
      </h4>
      <p>
        Kami dapat menampilkan, menyertakan, atau menyediakan konten pihak
        ketiga (termasuk data, informasi, aplikasi, dan layanan produk lainnya)
        atau menyediakan tautan ke situs web atau layanan pihak ketiga ("Layanan
        Pihak Ketiga").
      </p>
      <p>
        Anda mengakui dan menyetujui bahwa VHP Self Check-in tidak akan
        bertanggung jawab atas Layanan Pihak Ketiga mana pun, termasuk
        keakuratan, kelengkapan, ketepatan waktu, validitas, kepatuhan hak
        cipta, legalitas, kesopanan, kualitas, atau aspek lainnya daripadanya.
        VHP Online Check-in tidak berasumsi dan tidak akan memiliki tanggung
        jawab atau tanggung jawab apa pun kepada Anda atau orang atau entitas
        lain untuk Layanan Pihak Ketiga mana pun.
      </p>
      <p>
        Layanan pihak ketiga dan tautan yang ada hanya disediakan sebagai
        kenyamanan bagi Anda dan Anda mengakses dan menggunakannya sepenuhnya
        dengan risiko Anda sendiri dan tunduk pada syarat dan ketentuan pihak
        ketiga tersebut.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        Teknologi Pelacakan
      </h4>
      <p><b>Cookies</b></p>
      <p>
        Kami menggunakan Cookie untuk meningkatkan kinerja dan fungsionalitas
        situs web kami tetapi tidak penting untuk penggunaannya. Namun, tanpa
        cookie ini, fungsi tertentu seperti video mungkin menjadi tidak tersedia
        atau Anda akan diminta untuk memasukkan detail login Anda setiap kali
        Anda mengunjungi situs web karena kami tidak akan dapat mengingat bahwa
        Anda telah masuk sebelumnya.
      </p>
      <p><b>Penyimpanan Lokal</b></p>
      <p>
        Penyimpanan Lokal kadang-kadang dikenal sebagai penyimpanan DOM,
        menyediakan aplikasi web dengan metode dan protokol untuk menyimpan data
        sisi klien. Penyimpanan web mendukung penyimpanan data persisten, mirip
        dengan cookie tetapi dengan kapasitas yang sangat ditingkatkan dan tidak
        ada informasi yang disimpan di header permintaan HTTP.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        Informasi tentang Peraturan Perlindungan Data Umum (GDPR)
      </h4>
      <p>
        Kami mungkin mengumpulkan dan menggunakan informasi dari Anda jika Anda
        berasal dari Wilayah Ekonomi Eropa (EEA), dan di bagian ini Kebijakan
        Privasi kami, kami akan menjelaskan dengan tepat bagaimana dan mengapa
        data ini dikumpulkan, dan bagaimana kami mempertahankan data ini di
        bawah perlindungan agar tidak direplikasi atau digunakan dengan cara
        yang salah.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        Apa itu GDPR?
      </h4>
      <p>
        GDPR adalah undang-undang privasi dan perlindungan data di seluruh UE
        yang mengatur bagaimana data penduduk UE dilindungi oleh perusahaan dan
        meningkatkan kontrol yang dimiliki penduduk UE, atas data pribadi
        mereka.
      </p>
      <p>
        GDPR relevan untuk setiap perusahaan yang beroperasi secara global dan
        bukan hanya bisnis yang berbasis di Uni Eropa dan penduduk Uni Eropa.
        Data pelanggan kami penting terlepas dari lokasinya, itulah sebabnya
        kami telah menerapkan kontrol GDPR sebagai standar dasar kami untuk
        semua operasi kami di seluruh dunia.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        Apa itu data pribadi?
      </h4>
      <p>
        Setiap data yang terkait dengan individu yang dapat diidentifikasi atau
        diidentifikasi. GDPR mencakup spektrum informasi yang luas yang dapat
        digunakan sendiri, atau dikombinasikan dengan informasi lain, untuk
        mengidentifikasi seseorang. Data pribadi melampaui nama atau alamat
        email seseorang. Beberapa contoh termasuk informasi keuangan, pendapat
        politik, data genetik, data biometrik, alamat IP, alamat fisik,
        orientasi seksual, dan etnis.
      </p>
      <p>Prinsip Perlindungan Data meliputi persyaratan seperti:</p>
      <ul>
        <li>
          Data pribadi yang dikumpulkan harus diproses dengan cara yang adil,
          legal, dan transparan dan hanya boleh digunakan dengan cara yang
          diharapkan secara wajar oleh seseorang.
        </li>
        <li>
          Data pribadi hanya boleh dikumpulkan untuk memenuhi tujuan tertentu
          dan hanya boleh digunakan untuk tujuan itu. Organisasi harus
          menentukan mengapa mereka membutuhkan data pribadi saat mereka
          mengumpulkannya.
        </li>
        <li>
          Data pribadi harus dipegang tidak lebih dari yang diperlukan untuk
          memenuhi tujuannya.
        </li>
        <li>
          Orang-orang yang dicakup oleh GDPR memiliki hak untuk mengakses data
          pribadi mereka sendiri. Mereka juga dapat meminta salinan data mereka,
          dan data mereka diperbarui, dihapus, dibatasi, atau dipindahkan ke
          organisasi lain.
        </li>
      </ul>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        Mengapa GDPR penting?
      </h4>
      <p>
        GDPR menambahkan beberapa persyaratan baru mengenai bagaimana perusahaan
        harus melindungi data pribadi individu yang mereka kumpulkan dan proses.
        Ini juga meningkatkan taruhan untuk kepatuhan dengan meningkatkan
        penegakan dan memberlakukan denda yang lebih besar untuk pelanggaran. Di
        luar fakta-fakta ini itu hanya hal yang benar untuk dilakukan. Di Help
        Scout kami sangat percaya bahwa privasi data Anda sangat penting dan
        kami sudah memiliki praktik keamanan dan privasi yang solid yang
        melampaui persyaratan peraturan baru ini.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        Hak Subjek Data Individu - Akses Data, Portabilitas, dan Penghapusan
      </h4>
      <p>
        Kami berkomitmen untuk membantu pelanggan kami memenuhi persyaratan hak
        subjek data GDPR. VHP Self Check-in memproses atau menyimpan semua data
        pribadi dalam vendor yang sepenuhnya diperiksa dan mematuhi DPA. Kami
        menyimpan semua percakapan dan data pribadi hingga 6 tahun kecuali akun
        Anda dihapus. Dalam hal ini, kami membuang semua data sesuai dengan
        Ketentuan Layanan dan Kebijakan Privasi kami, tetapi kami tidak akan
        menahannya lebih dari 60 hari.
      </p>
      <p>
        Kami menyadari bahwa jika Anda bekerja dengan pelanggan UE, Anda harus
        dapat memberi mereka kemampuan untuk mengakses, memperbarui, mengambil,
        dan menghapus data pribadi. Kami menangkapmu! Kami telah disiapkan
        sebagai layanan mandiri sejak awal dan selalu memberi Anda akses ke data
        Anda dan data pelanggan Anda. Tim dukungan pelanggan kami ada di sini
        bagi Anda untuk menjawab pertanyaan apa pun yang mungkin Anda miliki
        tentang bekerja dengan API.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 30px !important;
          margin-bottom: 10px !important;
          line-height: 1.5rem !important;
        "
      >
        Hubungi Kami
      </h4>
      <p>Jangan ragu untuk menghubungi kami jika Anda memiliki pertanyaan.</p>
      <ul>
        <li>Email: <a href="mailto:info@sindata.net">info@sindata.net</a></li>
        <li>Telepon: (62) 21 - 50860678</li>
        <li>
          Website:
          <a href="https://www.sindata.net">https://www.sindata.net</a>
        </li>
        <li>
          Alamat: Jl. Bukit Gading Raya, Gading Bukit Indah Blok O No. 3-5,
          Jakarta 14240 - Indonesia
        </li>
      </ul>
    </div>`,
    },
  ],
};
