export default {
  responses: [
    {
      policy: `<div class="container">
      <p>
        VHP Self Check-in (“we,” “our,” or “us”) is committed to protecting your
        privacy. This Privacy Policy explains how your personal information is
        collected, used, and disclosed by VHP Self Check-in. This Privacy Policy
        applies to our website, and its associated subdomains (collectively, our
        “Service”) alongside our application, VHP Self Check-in. By accessing or
        using our Service, you signify that you have read, understood, and agree
        to our collection, storage, use, and disclosure of your personal
        information as described in this Privacy Policy and our Terms of
        Service.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 10px !important;
          margin-bottom: 0 !important;
        "
      >
        Definitions and Key Terms
      </h4>
      <p>
        To help explain things as clearly as possible in this Privacy Policy,
        every time any of these terms are referenced, are strictly defined as:
      </p>
      <ul>
        <li>
          Cookie: small amount of data generated by a website and saved by your
          web browser. It is used to identify your browser, provide analytics,
          remember information about you such as your language preference or
          login information.
        </li>
        <li>
          Company: when this policy mentions our “Company", "we," "us," or
          "our," it refers to PT. SUPRANUSA SINDATA, (Jl. Bukit Gading Raya,
          Gading Bukit Indah Blok O No. 3-5, Jakarta 14240 - Indonesia) that is
          responsible for your information under this Privacy Policy.
        </li>
        <li>
          Country: where VHP Self Check-in or the owners/founders of VHP Self
          Check-in are based, in this case is Indonesia.
        </li>
        <li>
          Customer: refers to the company, organization or person that signs up
          to use the VHP Self Check-in Service to manage the relationships with
          your consumers or service users.
        </li>
        <li>
          Device: any internet connected device such as a phone, tablet,
          computer or any other device that can be used to visit VHP Self
          Check-in and use the services.
        </li>
        <li>
          IP address: Every device connected to the Internet is assigned a
          number known as an Internet protocol (IP) address. These numbers are
          usually assigned in geographic blocks. An IP address can often be used
          to identify the location from which a device is connecting to the
          Internet.
        </li>
        <li>
          Personnel: refers to those individuals who are employed by Our
          Customer or are under contract to perform a service on behalf of one
          of the parties.
        </li>
        <li>
          Personal Data: any information that directly, indirectly, or in
          connection with other information - including a personal
          identification number - allows for the identification or
          identifiability of a natural person.
        </li>
        <li>
          Service: refers to the service provided by VHP Self Check-in as
          described in the relative terms (if available) and on this platform.
        </li>
        <li>
          Third-party service: refers to advertisers, contest sponsors,
          promotional and marketing partners, and others who provide our content
          or whose products or services we think may interest you.
        </li>
        <li>
          Website: VHP Self Check-in."’s" site, which can be accessed via this
          URL: <a href="https://vhp-online.com">https://vhp-online.com</a>.
        </li>
        <li>
          You: a person or entity that is registered with VHP Online Check-in to
          use the Services.
        </li>
      </ul>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 10px !important;
          margin-bottom: 0 !important;
        "
      >
        What information do we collect?
      </h4>
      <p>
        We collect information from you when you visit our website and do self
        check-in on our site, and also respond to a survey or fill out a form.
        All the information will directly send to Our Customer.
      </p>
      <ul>
        <li>Name / Username</li>
        <li>Phone Numbers</li>
        <li>Email Addresses</li>
        <li>Mailing Addresses</li>
        <li>Nationality</li>
        <li>Purpose of Stay</li>
        <li>Vehicle Registration Number</li>
        <li>Stay Preferences</li>
      </ul>
      <p>
        We also collect information from mobile devices, according to Our
        Customer Regulation for the purposes of recording the identity of guests
        staying at the hotel and to avoid identity fraud by ensuring that your
        identity matches the identity of the guest stated on the booking
        voucher.
      </p>
      <ul>
        <li>
          Photo Gallery (Pictures): Granting photo gallery access allows the
          user to upload ID Card / Passport Picture from their photo gallery or
          take a picture of their ID Card / Passport.
        </li>
      </ul>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 10px !important;
          margin-bottom: 0 !important;
        "
      >
        How do we use the information we collect?
      </h4>
      <p>
        Any of the information we collect from you are directly send to Our
        Customer and may be used in one of the following ways:
      </p>
      <ul>
        <li>
          To personalize your experience (your information may helps Our
          Customer to better respond to your individual needs).
        </li>
        <li>
          To improve customer service (your information may helps Our Customer
          to more effectively respond to your customer service requests and
          support needs).
        </li>
        <li>To process transactions.</li>
        <li>To send periodic emails.</li>
      </ul>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 10px !important;
          margin-bottom: 0 !important;
        "
      >
        Where and when is information collected from end users?
      </h4>
      <p>
        VHP Self Check-in will collect personal information that you submit to
        us.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 10px !important;
          margin-bottom: 0 !important;
        "
      >
        How Do We Use Your Email Address?
      </h4>
      <p>
        By submitting your email address on this website, you agree to receive
        emails from us to inform about the room is ready for you and also you
        can continue the check-in process. We only send email to people who have
        authorized us to contact them. We do not send unsolicited commercial
        emails, because we hate spam as much as you do. By submitting your email
        address, you also agree to allow Our Customer to collect your email
        address for sending the additional information.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 10px !important;
          margin-bottom: 0 !important;
        "
      >
        How Long Do We Keep Your Information?
      </h4>
      <p>
        We keep your information only so long as we need it to provide VHP Self
        Check-in to you and fulfill the purposes described in this policy. When
        we no longer need to use your information and there is no need for us to
        keep it to comply with our legal or regulatory obligations, we’ll either
        remove it from our systems or depersonalize it so that we can't identify
        you.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 10px !important;
          margin-bottom: 0 !important;
        "
      >
        How Do We Protect Your Information?
      </h4>
      <p>
        We implement a variety of security measures to maintain the safety of
        your personal information when you place an order or enter, submit, or
        access your personal information. We offer the use of a secure server.
        All supplied sensitive/credit information is transmitted via Secure
        Socket Layer (SSL) technology and then encrypted into our Payment
        gateway providers database only to be accessible by those authorized
        with special access rights to such systems, and are required to keep the
        information confidential. After a transaction, your private information
        (credit cards, social security numbers, financials, etc.) is never kept
        on file. We cannot, however, ensure or warrant the absolute security of
        any information you transmit to VHP Self Check-in or guarantee that your
        information on the Service may not be accessed, disclosed, altered, or
        destroyed by a breach of any of our physical, technical, or managerial
        safeguards.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 10px !important;
          margin-bottom: 0 !important;
        "
      >
        Could my information be transferred to other countries?
      </h4>
      <p>
        VHP Self Check-in is incorporated in Indonesia. Information collected
        via our website, through direct interactions with you, or from use of
        our help services may be transferred from time to time to our offices or
        personnel, to our customer, or to third parties, located throughout the
        world, and may be viewed and hosted anywhere in the world, including
        countries that may not have laws of general applicability regulating the
        use and transfer of such data. To the fullest extent allowed by
        applicable law, by using any of the above, you voluntarily consent to
        the trans-border transfer and hosting of such information.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 10px !important;
          margin-bottom: 0 !important;
        "
      >
        Is the information collected through the VHP Self Check-In Service
        secure?
      </h4>
      <p>
        We take precautions to protect the security of your information. We have
        physical, electronic, and managerial procedures to help safeguard,
        prevent unauthorized access, maintain data security, and correctly use
        your information. However, neither people nor security systems are
        foolproof, including encryption systems. In addition, people can commit
        intentional crimes, make mistakes or fail to follow policies. Therefore,
        while we use reasonable efforts to protect your personal information, we
        cannot guarantee its absolute security. If applicable law imposes any
        non-disclaimable duty to protect your personal information, you agree
        that intentional misconduct will be the standards used to measure our
        compliance with that duty.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 10px !important;
          margin-bottom: 0 !important;
        "
      >
        Can I update or correct my information?
      </h4>
      <p>
        The rights you have to request updates or corrections to the information
        VHP Self Check-In collects depend on your relationship with Our
        Customer. Personnel may update or correct their information as detailed
        in their internal customer employment policies.
      </p>
      <p>
        Customers have the right to request the restriction of certain uses and
        disclosures of personally identifiable information as follows. You can
        contact Our Customer in order to (1) update or correct your personally
        identifiable information, (2) change your preferences with respect to
        communications and other information you receive from us, or (3) delete
        the personally identifiable information maintained about you on our
        systems. Such updates, corrections, changes and deletions will have no
        effect on other information that we maintain, or information that we
        have provided to third parties in accordance with this Privacy Policy
        prior to such update, correction, change or deletion.
      </p>
      <p>
        You should be aware that it is not technologically possible to remove
        each and every record of the information you have provided to us from
        our system. The need to back up our systems to protect information from
        inadvertent loss means that a copy of your information may exist in a
        non-erasable form that will be difficult or impossible for us to locate.
        Promptly after receiving your request, all personal information stored
        in databases we actively use, and other readily searchable media will be
        updated, corrected, changed or deleted, as appropriate, as soon as and
        to the extent reasonably and technically practicable.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 10px !important;
          margin-bottom: 0 !important;
        "
      >
        Governing Law
      </h4>
      <p>
        This Privacy Policy is governed by the laws of Indonesia without regard
        to its conflict of laws provision. You consent to the exclusive
        jurisdiction of the courts in connection with any action or dispute
        arising between the parties under or in connection with this Privacy
        Policy except for those individuals who may have rights to make claims
        under Privacy Shield, or the Swiss-US framework.
      </p>
      <p>
        The laws of Indonesia, excluding its conflicts of law rules, shall
        govern this Agreement and your use of the website. Your use of the
        website may also be subject to other local, state, national, or
        international laws.
      </p>
      <p>
        By using VHP Self Check-in or contacting us directly, you signify your
        acceptance of this Privacy Policy. If you do not agree to this Privacy
        Policy, you should not engage with our website, or use our services.
        Continued use of the website, direct engagement with us, or following
        the posting of changes to this Privacy Policy that do not significantly
        affect the use or disclosure of your personal information will mean that
        you accept those changes.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 10px !important;
          margin-bottom: 0 !important;
        "
      >
        Your Consent
      </h4>
      <p>
        We've updated our Privacy Policy to provide you with complete
        transparency into what is being set when you visit our site and how it's
        being used. By using our website, filling the form, or making a
        purchase, you hereby consent to our Privacy Policy and agree to its
        terms.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 10px !important;
          margin-bottom: 0 !important;
        "
      >
        Links to Other Websites
      </h4>
      <p>
        This Privacy Policy applies only to the Services. The Services may
        contain links to other websites not operated or controlled by VHP Self
        Check-in. We are not responsible for the content, accuracy or opinions
        expressed in such websites, and such websites are not investigated,
        monitored or checked for accuracy or completeness by us. Please remember
        that when you use a link to go from the Services to another website, our
        Privacy Policy is no longer in effect. Your browsing and interaction on
        any other website, including those that have a link on our platform, is
        subject to that website’s own rules and policies. Such third parties may
        use their own cookies or other methods to collect information about you.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 10px !important;
          margin-bottom: 0 !important;
        "
      >
        Cookies
      </h4>
      <p>
        VHP Self Check-in uses "Cookies" to identify the areas of our website
        that you have visited. A Cookie is a small piece of data stored on your
        computer or mobile device by your web browser. We use Cookies to enhance
        the performance and functionality of our website but are non-essential
        to their use. However, without these cookies, certain functionality may
        become. Most web browsers can be set to disable the use of Cookies.
        However, if you disable Cookies, you may not be able to access
        functionality on our website correctly or at all. We never place
        Personally Identifiable Information in Cookies.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 10px !important;
          margin-bottom: 0 !important;
        "
      >
        Blocking and disabling cookies and similar technologies
      </h4>
      <p>
        Wherever you're located you may also set your browser to block cookies
        and similar technologies, but this action may block our essential
        cookies and prevent our website from functioning properly, and you may
        not be able to fully utilize all of its features and services. You
        should also be aware that you may also lose some saved information (e.g.
        saved login details, site preferences) if you block cookies on your
        browser. Different browsers make different controls available to you.
        Disabling a cookie or category of cookie does not delete the cookie from
        your browser, you will need to do this yourself from within your
        browser, you should visit your browser's help menu for more information.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 10px !important;
          margin-bottom: 0 !important;
        "
      >
        Payment Details
      </h4>
      <p>
        In respect to any credit card or other payment processing details you
        have provided us, we commit that this confidential information will be
        stored in the most secure manner possible.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 10px !important;
          margin-bottom: 0 !important;
        "
      >
        Kids' Privacy
      </h4>
      <p>
        We do not address anyone under the age of 12. We do not knowingly
        collect personally identifiable information from anyone under the age of
        12. If You are a parent or guardian and You are aware that Your child
        has provided Us with Personal Data, please contact Us. If We become
        aware that We have collected Personal Data from anyone under the age of
        12 without verification of parental consent, We take steps to remove
        that information from Our servers.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 10px !important;
          margin-bottom: 0 !important;
        "
      >
        Changes To Our Privacy Policy
      </h4>
      <p>
        We may change our Service and policies, and we may need to make changes
        to this Privacy Policy so that they accurately reflect our Service and
        policies. Unless otherwise required by law, we will notify you (for
        example, through our Service) before we make changes to this Privacy
        Policy and give you an opportunity to review them before they go into
        effect. Then, if you continue to use the Service, you will be bound by
        the updated Privacy Policy.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 10px !important;
          margin-bottom: 0 !important;
        "
      >
        Third-Party Services
      </h4>
      <p>
        We may display, include or make available third-party content (including
        data, information, applications and other products services) or provide
        links to third-party websites or services ("Third- Party Services").
      </p>
      <p>
        You acknowledge and agree that VHP Self Check-In shall not be
        responsible for any Third-Party Services, including their accuracy,
        completeness, timeliness, validity, copyright compliance, legality,
        decency, quality or any other aspect thereof. VHP Self Check-In does not
        assume and shall not have any liability or responsibility to you or any
        other person or entity for any Third-Party Services.
      </p>
      <p>
        Third-Party Services and links thereto are provided solely as a
        convenience to you and you access and use them entirely at your own risk
        and subject to such third parties' terms and conditions.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 10px !important;
          margin-bottom: 0 !important;
        "
      >
        Tracking Technologies
      </h4>
      <b>Cookies</b>
      <p>
        We use Cookies to enhance the performance and functionality of our
        website but are non-essential to their use. However, without these
        cookies, certain functionality may become unavailable.
      </p>
      <b>Local Storage</b>
      <p>
        Local Storage sometimes known as DOM storage, provides web apps with
        methods and protocols for storing client-side data. Web storage supports
        persistent data storage, similar to cookies but with a greatly enhanced
        capacity and no information stored in the HTTP request header.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 10px !important;
          margin-bottom: 0 !important;
        "
      >
        Information about General Data Protection Regulation (GDPR)
      </h4>
      <p>
        We may be collecting and using information from you if you are from the
        European Economic Area (EEA), and in this section of our Privacy Policy
        we are going to explain exactly how and why is this data collected, and
        how we maintain this data under protection from being replicated or used
        in the wrong way.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 10px !important;
          margin-bottom: 0 !important;
        "
      >
        What is GDPR?
      </h4>
      <p>
        GDPR is an EU-wide privacy and data protection law that regulates how EU
        residents' data is protected by companies and enhances the control the
        EU residents have, over their personal data.
      </p>
      <p>
        The GDPR is relevant to any globally operating company and not just the
        EU-based businesses and EU residents. Our customers’ data is important
        irrespective of where they are located, which is why we have implemented
        GDPR controls as our baseline standard for all our operations worldwide.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 10px !important;
          margin-bottom: 0 !important;
        "
      >
        What is personal data?
      </h4>
      <p>
        Any data that relates to an identifiable or identified individual. GDPR
        covers a broad spectrum of information that could be used on its own, or
        in combination with other pieces of information, to identify a person.
        Personal data extends beyond a person’s name or email address. Some
        examples include financial information, political opinions, genetic
        data, biometric data, IP addresses, physical address, sexual
        orientation, and ethnicity.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 10px !important;
          margin-bottom: 0 !important;
        "
      >
        The Data Protection Principles include requirements such as:
      </h4>
      <ul>
        <li>
          Personal data collected must be processed in a fair, legal, and
          transparent way and should only be used in a way that a person would
          reasonably expect.
        </li>
        <li>
          Personal data should only be collected to fulfil a specific purpose
          and it should only be used for that purpose. Organizations must
          specify why they need the personal data when they collect it.
        </li>
        <li>
          Personal data should be held no longer than necessary to fulfil its
          purpose.
        </li>
        <li>
          People covered by the GDPR have the right to access their own personal
          data. They can also request a copy of their data, and that their data
          be updated, deleted, restricted, or moved to another organization.
        </li>
      </ul>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 10px !important;
          margin-bottom: 0 !important;
        "
      >
        Why is GDPR important?
      </h4>
      <p>
        GDPR adds some new requirements regarding how companies should protect
        individuals' personal data that they collect and process. It also raises
        the stakes for compliance by increasing enforcement and imposing greater
        fines for breach. Beyond these facts it's simply the right thing to do.
        At Help Scout we strongly believe that your data privacy is very
        important and we already have solid security and privacy practices in
        place that go beyond the requirements of this new regulation.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 10px !important;
          margin-bottom: 0 !important;
        "
      >
        Individual Data Subject's Rights - Data Access, Portability and Deletion
      </h4>
      <p>
        Individual Data Subject's Rights - Data Access, Portability and Deletion
        We are committed to helping our customers meet the data subject rights
        requirements of GDPR. VHP Self Check-in processes or stores all personal
        data in fully vetted, DPA compliant vendors. We do store all
        conversation and personal data for up to 6 years unless your account is
        deleted. In which case, we dispose of all data in accordance with our
        Terms of Service and Privacy Policy, but we will not hold it longer than
        60 days.
      </p>
      <p>
        We are aware that if you are working with EU customers, you need to be
        able to provide them with the ability to access, update, retrieve and
        remove personal data. We got you! We've been set up as self service from
        the start and have always given you access to your data and your
        customers data. Our customer support team is here for you to answer any
        questions you might have about working with the API.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 10px !important;
          margin-bottom: 0 !important;
        "
      >
        Contact Us
      </h4>
      <p>Don't hesitate to contact us if you have any questions.</p>
      <ul>
        <li>Email: <a href="mailto:info@sindata.net">info@sindata.net</a></li>
        <li>Phone Number: (62) 21 - 50860678</li>
        <li>
          Website:
          <a href="https://www.sindata.net">https://www.sindata.net</a>
        </li>
        <li>
          Address: Jl. Bukit Gading Raya, Gading Bukit Indah Blok O No. 3-5,
          Jakarta 14240 - Indonesia
        </li>
      </ul>
    </div>`,

      policeTrans: `<div class="container">
      <p>
        VHP Self Check-In ("kami" atau "kita") berkomitmen untuk melindungi
        privasi Anda. Kebijakan Privasi ini menjelaskan bagaimana informasi
        pribadi Anda dikumpulkan, digunakan, dan diungkapkan oleh VHP Self
        Check-In. Kebijakan Privasi ini berlaku untuk situs web kami, dan
        subdomain terkait (secara kolektif, "Layanan" kami) bersama aplikasi
        kami, VHP Self Check-In. Dengan mengakses atau menggunakan Layanan kami,
        Anda menandakan bahwa Anda telah membaca, memahami, dan menyetujui
        pengumpulan, penyimpanan, penggunaan, dan pengungkapan informasi pribadi
        Anda sebagaimana dijelaskan dalam Kebijakan Privasi ini dan Ketentuan
        Layanan kami.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 10px !important;
          margin-bottom: 0 !important;
        "
      >
        Informasi Apa yang Kami Kumpulkan?
      </h4>
      <p>
        Kami mengumpulkan informasi dari Anda ketika Anda mengunjungi situs web
        kami, mendaftar di situs kami, melakukan pemesanan, berlangganan buletin
        kami, menanggapi survei atau mengisi formulir.
      </p>
      <ul>
        <li>
          Cookie: sejumlah kecil data yang dihasilkan oleh situs web dan
          disimpan oleh browser web Anda. Ini digunakan untuk mengidentifikasi
          browser Anda, menyediakan analitik, mengingat informasi tentang Anda
          seperti preferensi bahasa atau informasi login Anda.
        </li>
        <li>
          Perusahaan: ketika kebijakan ini menyebutkan "Perusahaan" kami,
          "kami," atau "kita," itu mengacu pada PT. SUPRANUSA SINDATA, (Jl.
          Bukit Gading Raya, Gading Bukit Indah Blok O No. 3-5, Jakarta 14240 -
          Indonesia) yang bertanggung jawab atas informasi Anda berdasarkan
          Kebijakan Privasi ini.
        </li>
        <li>
          Country: di mana VHP Self Check-in atau pemilik/pendiri VHP Self
          Check-in berbasis, dalam hal ini adalah Indonesia.
        </li>
        <li>
          Pelanggan: mengacu pada perusahaan, organisasi, atau orang yang
          mendaftar untuk menggunakan Layanan VHP Self Check-In untuk mengelola
          hubungan dengan konsumen atau pengguna layanan Anda.
        </li>
        <li>
          Perangkat: perangkat apa pun yang terhubung ke internet seperti
          ponsel, tablet, komputer, atau perangkat lain yang dapat digunakan
          untuk mengunjungi VHP Self Check-In dan menggunakan layanan.
        </li>
        <li>
          Alamat IP: Setiap perangkat yang terhubung ke Internet diberi nomor
          yang dikenal sebagai alamat protokol Internet (IP). Angka-angka ini
          biasanya ditetapkan dalam blok geografis. Alamat IP sering dapat
          digunakan untuk mengidentifikasi lokasi tempat perangkat terhubung ke
          Internet.
        </li>
        <li>
          Personil: mengacu pada orang-orang yang dipekerjakan oleh VHP Self
          Check-In atau berada di bawah kontrak untuk melakukan layanan atas
          nama salah satu pihak.
        </li>
        <li>
          Data Pribadi: setiap informasi yang secara langsung, tidak langsung,
          atau sehubungan dengan informasi lain - termasuk nomor identifikasi
          pribadi - memungkinkan untuk identifikasi atau identifikasi orang
          alami.
        </li>
        <li>
          Service: mengacu pada layanan yang disediakan oleh VHP Self Check-In
          sebagaimana dijelaskan dalam istilah relatif (jika tersedia) dan pada
          platform ini.
        </li>
        <li>
          Layanan pihak ketiga: mengacu pada pengiklan, sponsor kontes, mitra
          promosi dan pemasaran, dan lainnya yang menyediakan konten kami atau
          yang produk atau layanannya menurut kami mungkin menarik bagi Anda.
        </li>
        <li>
          Situs Web: VHP Self Check-in." s" situs, yang dapat diakses melalui
          URL ini: <a href="https://vhp-online.com">https://vhp-online.com</a>.
        </li>
        <li>
          Anda: seseorang atau entitas yang terdaftar di VHP Self Check-In untuk
          menggunakan Layanan.
        </li>
      </ul>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 10px !important;
          margin-bottom: 0 !important;
        "
      >
        Informasi Apa yang Kami Kumpulkan?
      </h4>
      <p>
        Kami mengumpulkan informasi dari Anda ketika Anda mengunjungi situs web
        kami dan melakukan check-in dari situs kami, dan juga menanggapi survei
        atau mengisi formulir. Keseluruhan informasi akan dikirim langsung pada
        Pelanggan Kami.
      </p>
      <ul>
        <li>Nama / Nama user</li>
        <li>Nomor Telepon</li>
        <li>Alamat Email</li>
        <li>Alamat Surat Menyurat</li>
        <li>Kebangsaan</li>
        <li>Tujuan Menginap</li>
        <li>Nomor Plat Kendaraan</li>
        <li>Preferensi Menginap</li>
      </ul>
      <p>
        Kami juga mengumpulkan informasi dari perangkat seluler untuk keperluan
        pendataan identitas tamu yang menginap di hotel serta untuk menghindari
        penipuan identitas dengan memastikan bahwa identitas Anda cocok dengan
        identitas tamu yang tertera di voucher pemesanan:
      </p>
      <ul>
        <li>
          Galeri Foto (Gambar): Memberikan akses galeri foto memungkinkan
          pengguna untuk mengunggah Gambar KTP / Paspor dari galeri foto anda
          atau mengambil gambar KTP / Paspor anda.
        </li>
      </ul>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 10px !important;
          margin-bottom: 0 !important;
        "
      >
        Bagaimana kami menggunakan informasi yang kami kumpulkan?
      </h4>
      <p>
        Salah satu informasi yang kami kumpulkan dari Anda secara langsung akan
        dikirim kepada Pelanggan Kami dapat digunakan dengan salah satu cara
        berikut:
      </p>
      <ul>
        <li>
          Untuk mempersonalisasi pengalaman Anda (informasi Anda membantu kami
          merespons kebutuhan individu Anda dengan lebih baik).
        </li>
        <li>
          Untuk meningkatkan layanan pelanggan (informasi Anda membantu kami
          untuk lebih efektif menanggapi permintaan layanan pelanggan dan
          kebutuhan dukungan Anda).
        </li>
        <li>Untuk memproses transaksi.</li>
        <li>Untuk mengirim email berkala.</li>
      </ul>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 10px !important;
          margin-bottom: 0 !important;
        "
      >
        Dimana dan kapan informasi dikumpulkan dari pengguna akhir?
      </h4>
      <p>
        VHP Self Check-in akan mengumpulkan informasi pribadi yang Anda kirimkan
        kepada kami.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 10px !important;
          margin-bottom: 0 !important;
        "
      >
        Bagaimana kami menggunakan alamat email anda?
      </h4>
      <p>
        Dengan mengirimkan alamat email Anda pada website ini, maka Anda setuju
        untuk menerima email dari kami untuk menginformasikan tentang kamar yang
        sudah siap untuk Anda dan juga Anda dapat melanjutkan proses check-in.
        Kami hanya mengirim email ke orang yang telah mengizinkan kami untuk
        menghubungi mereka. Kami tidak mengirimkan email komersial yang tidak
        diminta, karena kami membenci span seperti halnya Anda. Dengan
        mengirimkan alamat email Anda, Anda juga setuju untuk mengizinkan
        Pelanggan Kami mengumpulkan alamat email Anda untuk mengirimkan
        informasi tambahan.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 10px !important;
          margin-bottom: 0 !important;
        "
      >
        Berapa lama kami menyimpan informasi Anda?
      </h4>
      <p>
        Kami menyimpan informasi Anda hanya selama kami membutuhkannya untuk
        memberikan layanan VHP Self Check-In kepada Anda dan memenuhi tujuan
        yang dijelaskan dalam kebijakan ini. Jika kami tidak perlu lagi
        menggunakan informasi Anda dan kami tidak perlu menyimpannya untuk
        mematuhi kewajiban hukum atau peraturan kami, kami akan menghapusnya
        dari sistem kami atau membatalkannya sehingga kami tidak dapat
        mengidentifikasi Anda.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 10px !important;
          margin-bottom: 0 !important;
        "
      >
        Bagaimana kami melindungi informasi Anda?
      </h4>
      <p>
        Kami menerapkan berbagai langkah keamanan untuk menjaga keamanan
        informasi pribadi Anda saat anda melakukan pemesanan atau memasukkan,
        mengirimkan, atau mengakses informasi pribadi Anda. Kami menawarkan
        penggunaan server yang aman. Semua informasi sensitif / kredit yang
        diberikan dikirimkan melalui teknologi Secure Socket Layer (SSL) dan
        kemudian dienkripsi ke dalam database penyedia gateway pembayaran kami
        hanya untuk dapat diakses oleh mereka yang berwenang dengan hak akses
        khusus ke sistem tersebut, dan diharuskan untuk menjaga kerahasiaan
        informasi tersebut. Setelah transaksi, informasi pribadi Anda (kartu
        kredit, nomor jaminan sosial, keuangan, dll.) tidak pernah disimpan
        dalam file. Namun, kami tidak dapat memastikan atau menjamin keamanan
        mutlak dari informasi apapun yang Anda kirimkan ke VHP Self Check-In
        atau menjamin bahwa informasi Anda pada Layanan tidak dapat diakses,
        diungkapkan, diubah, atau dihancurkan oleh pelanggaran fisik kami,
        pengamanan teknis, atau manajerial.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 10px !important;
          margin-bottom: 0 !important;
        "
      >
        Bisakah informasi saya ditransfer ke negara lain?
      </h4>
      <p>
        VHP Self Check-in didirikan di Indonesia. Informasi yang dikumpulkan
        melalui situs web kami, melalui interaksi langsung dengan Anda, atau
        dari penggunaan layanan bantuan kami dapat ditransfer dari waktu ke
        waktu ke kantor atau personel kami, ke pelanggan kami, atau ke pihak
        ketiga, yang berlokasi di seluruh dunia, dan dapat dilihat dan
        dihosting. di mana pun di dunia, termasuk negara yang mungkin tidak
        memiliki undang-undang yang berlaku umum yang mengatur penggunaan dan
        transfer data semacam itu. Sejauh diizinkan oleh hukum yang berlaku,
        dengan menggunakan salah satu dari yang di atas, Anda secara sukarela
        menyetujui transfer lintas batas dan menampung informasi tersebut.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 10px !important;
          margin-bottom: 0 !important;
        "
      >
        Apakah informasi yang dikumpulkan melalui Layanan VHP Self Check-In
        aman?
      </h4>
      <p>
        Kami mengambil tindakan pencegahan untuk melindungi keamanan informasi
        Anda. Kami memiliki prosedur fisik, elektronik, dan manajerial untuk
        membantu melindungi, mencegah akses yang tidak sah, menjaga keamanan
        data, dan menggunakan informasi Anda dengan benar. Namun, baik orang
        maupun sistem keamanan tidak bisa dibilang sangat mudah, termasuk sistem
        enkripsi. Selain itu, orang dapat melakukan kejahatan yang disengaja,
        membuat kesalahan, atau gagal mengikuti kebijakan. Oleh karena itu,
        meskipun kami menggunakan upaya yang wajar untuk melindungi informasi
        pribadi Anda, kami tidak dapat menjamin keamanan mutlaknya. Jika
        undang-undang yang berlaku memberlakukan kewajiban yang tidak dapat
        diklaim untuk melindungi informasi pribadi Anda, Anda setuju bahwa
        kesalahan yang disengaja akan menjadi standar yang digunakan untuk
        mengukur kepatuhan kita terhadap kewajiban tersebut.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 10px !important;
          margin-bottom: 0 !important;
        "
      >
        Dapatkah saya memperbarui atau mengoreksi informasi saya?
      </h4>
      <p>
        Hak yang Anda miliki untuk meminta pembaruan atau koreksi atas informasi
        yang dikumpulkan oleh VHP Self Check-In bergantung pada hubungan Anda
        dengan Pelanggan Kami. Personil dapat memperbarui atau memperbaiki
        informasi mereka seperti yang dijelaskan dalam kebijakan ketenagakerjaan
        pelanggan internal mereka.
      </p>
      <p>
        Pelanggan memiliki hak untuk meminta pembatasan penggunaan tertentu dan
        pengungkapan informasi pengenal pribadi sebagai berikut. Anda dapat
        menghubungi Pelanggan Kami untuk (1) memperbarui atau memperbaiki
        informasi pribadi Anda, (2) mengubah preferensi Anda sehubungan dengan
        komunikasi dan informasi lain yang Anda terima dari kami, atau (3)
        menghapus informasi pribadi yang disimpan tentang Anda pada sistem kami.
        Pembaruan, koreksi, perubahan, dan penghapusan tersebut tidak akan
        berpengaruh pada informasi lain yang kami simpan, atau informasi yang
        kami berikan kepada pihak ketiga sesuai dengan Kebijakan Privasi ini
        sebelum pembaruan, koreksi, perubahan, atau penghapusan tersebut.
      </p>
      <p>
        Anda harus menyadari bahwa secara teknologi tidak mungkin untuk
        menghapus setiap catatan informasi yang Anda berikan kepada kami dari
        sistem kami. Kebutuhan untuk mencadangkan sistem kami untuk melindungi
        informasi dari kehilangan yang tidak disengaja berarti bahwa salinan
        informasi Anda mungkin ada dalam bentuk yang tidak dapat dihapus yang
        akan sulit atau tidak mungkin kami temukan. Segera setelah menerima
        permintaan Anda, semua informasi pribadi yang disimpan dalam database
        yang kami gunakan secara aktif, dan media lain yang mudah dicari akan
        diperbarui, dikoreksi, diubah atau dihapus, sebagaimana mestinya,
        secepat dan sejauh secara wajar dan praktis secara teknis.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 10px !important;
          margin-bottom: 0 !important;
        "
      >
        Peraturan Pemerintah
      </h4>
      <p>
        Kebijakan Privasi ini diatur oleh hukum Indonesia tanpa memperhatikan
        pertentangan ketentuan hukum. Anda menyetujui yurisdiksi eksklusif
        pengadilan sehubungan dengan tindakan atau perselisihan apa pun yang
        timbul antara para pihak di bawah atau sehubungan dengan Kebijakan
        Privasi ini kecuali untuk individu yang mungkin memiliki hak untuk
        membuat klaim di bawah Perlindungan Privasi, atau kerangka kerja
        Swiss-AS.
      </p>
      <p>
        Hukum Indonesia, tidak termasuk aturan hukum konflik, akan mengatur
        Perjanjian ini dan penggunaan Anda atas situs web. Penggunaan Anda atas
        situs web ini mungkin juga tunduk pada hukum lokal, negara bagian,
        nasional, atau internasional lainnya.
      </p>
      <p>
        Dengan menggunakan VHP Self Check-In atau menghubungi kami secara
        langsung, Anda menandakan penerimaan Anda terhadap Kebijakan Privasi
        ini. Jika Anda tidak setuju dengan Kebijakan Privasi ini, Anda tidak
        boleh terlibat dengan situs web kami, atau menggunakan layanan kami.
        Penggunaan situs web yang berkelanjutan, keterlibatan langsung dengan
        kami, atau setelah posting perubahan pada Kebijakan Privasi ini yang
        tidak secara signifikan memengaruhi penggunaan atau pengungkapan
        informasi pribadi Anda, berarti Anda menerima perubahan tersebut.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 10px !important;
          margin-bottom: 0 !important;
        "
      >
        Pertujuan Anda
      </h4>
      <p>
        Kami telah memperbarui Kebijakan Privasi kami untuk memberi Anda
        transparansi lengkap tentang apa yang disetel ketika Anda mengunjungi
        situs kami dan bagaimana itu digunakan. Dengan menggunakan situs web
        kami, mengisi formulir, atau melakukan pembelian, Anda dengan ini
        menyetujui Kebijakan Privasi kami dan menyetujui persyaratannya.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 10px !important;
          margin-bottom: 0 !important;
        "
      >
        Links to Other Websites
      </h4>
      <p>
        Kebijakan Privasi ini hanya berlaku untuk Layanan. Layanan dapat berisi
        tautan ke situs web lain yang tidak dioperasikan atau dikendalikan oleh
        VHP Self Check-in. Kami tidak bertanggung jawab atas konten, keakuratan,
        atau opini yang diungkapkan dalam situs web tersebut, dan situs web
        tersebut tidak diselidiki, dipantau, atau diperiksa untuk akurasi atau
        kelengkapan oleh kami. Harap diingat bahwa ketika Anda menggunakan
        tautan untuk pergi dari Layanan ke situs web lain, Kebijakan Privasi
        kami tidak lagi berlaku. Penjelajahan dan interaksi Anda di situs web
        lain, termasuk yang memiliki tautan di platform kami, tunduk pada aturan
        dan kebijakan situs web itu sendiri. Pihak ketiga tersebut dapat
        menggunakan cookie mereka sendiri atau metode lain untuk mengumpulkan
        informasi tentang Anda.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 10px !important;
          margin-bottom: 0 !important;
        "
      >
        Cookies
      </h4>
      <p>
        VHP Self Check-in menggunakan "Cookies" untuk mengidentifikasi area
        situs web kami yang telah Anda kunjungi. Cookie adalah sepotong kecil
        data yang disimpan di komputer atau perangkat seluler Anda oleh browser
        web Anda. Kami menggunakan Cookies untuk meningkatkan kinerja dan
        fungsionalitas situs web kami tetapi tidak penting untuk penggunaannya.
        Namun, tanpa cookie ini, fungsionalitas tertentu mungkin terjadi.
        Sebagian besar browser web dapat disetel untuk menonaktifkan penggunaan
        Cookies. Namun, jika Anda menonaktifkan Cookies, Anda mungkin tidak
        dapat mengakses fungsionalitas di situs web kami dengan benar atau sama
        sekali. Kami tidak pernah menempatkan Informasi Identitas Pribadi dalam
        Cookie.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 10px !important;
          margin-bottom: 0 !important;
        "
      >
        Memblokir dan menonaktifkan cookie dan teknologi serupa
      </h4>
      <p>
        Di mana pun Anda berada, Anda juga dapat menyetel browser Anda dan
        teknologi serupa, tetapi tindakan ini dapat memblokir cookie penting
        kami dan mencegah situs web kami berfungsi dengan baik, dan Anda mungkin
        tidak dapat menggunakan sepenuhnya semua fitur dan layanannya. Anda juga
        harus menyadari bahwa Anda mungkin juga kehilangan beberapa informasi
        yang disimpan (misalnya detail login yang disimpan, preferensi situs)
        jika Anda memblokir cookie di browser Anda. Browser yang berbeda membuat
        kontrol yang berbeda tersedia untuk Anda. Menonaktifkan cookie atau
        kategori cookie tidak menghapus cookie dari browser Anda, Anda harus
        melakukannya sendiri dari dalam browser Anda, Anda harus mengunjungi
        menu bantuan browser Anda untuk informasi lebih lanjut.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 10px !important;
          margin-bottom: 0 !important;
        "
      >
        Rincian Pembayaran
      </h4>
      <p>
        Sehubungan dengan kartu kredit atau rincian pemrosesan pembayaran lain
        yang Anda berikan kepada kami, kami berkomitmen bahwa informasi rahasia
        ini akan disimpan dengan cara yang paling aman.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 10px !important;
          margin-bottom: 0 !important;
        "
      >
        Privasi Anak-Anak
      </h4>
      <p>
        Kami tidak membahas siapa pun yang berusia di bawah 12 tahun. Kami tidak
        dengan sengaja mengumpulkan informasi yang dapat diidentifikasi secara
        pribadi dari siapa pun yang berusia di bawah 12 tahun. Jika Anda adalah
        orang tua atau wali dan Anda mengetahui bahwa anak Anda telah memberikan
        Data Pribadi kepada Kami, silakan hubungi Kami. Jika Kami mengetahui
        bahwa Kami telah mengumpulkan Data Pribadi dari siapa pun yang berusia
        di bawah 12 tahun tanpa verifikasi izin orang tua, Kami mengambil
        langkah-langkah untuk menghapus informasi tersebut dari server Kami.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 10px !important;
          margin-bottom: 0 !important;
        "
      >
        Perubahan Kebijakan Privasi Kami
      </h4>
      <p>
        Kami dapat mengubah Layanan dan kebijakan kami, dan kami mungkin perlu
        membuat perubahan pada Kebijakan Privasi ini sehingga secara akurat
        mencerminkan Layanan dan kebijakan kami. Kecuali jika diwajibkan oleh
        hukum, kami akan memberi tahu Anda (misalnya, melalui Layanan kami)
        sebelum kami membuat perubahan pada Kebijakan Privasi ini dan memberi
        Anda kesempatan untuk meninjaunya sebelum diberlakukan. Kemudian, jika
        Anda terus menggunakan Layanan, Anda akan terikat oleh Kebijakan Privasi
        yang diperbarui.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 10px !important;
          margin-bottom: 0 !important;
        "
      >
        Layanan Pihak Ketiga
      </h4>
      <p>
        Kami dapat menampilkan, memasukkan, atau menyediakan konten pihak ketiga
        (termasuk data, informasi, aplikasi, dan layanan produk lainnya) atau
        menyediakan tautan ke situs web atau layanan pihak ketiga ("Layanan
        Pihak Ketiga").
      </p>
      <p>
        Anda mengakui dan setuju bahwa VHP Self Check-In tidak bertanggung jawab
        atas Layanan Pihak Ketiga, termasuk keakuratan, kelengkapan, ketepatan
        waktu, validitas, kepatuhan hak cipta, legalitas, kesopanan, kualitas,
        atau aspek lain apa pun darinya. VHP Self Check-In tidak menganggap dan
        tidak memiliki kewajiban atau tanggung jawab apa pun kepada Anda atau
        orang atau entitas lain untuk Layanan Pihak Ketiga mana pun.
      </p>
      <p>
        Layanan Pihak Ketiga dan tautannya disediakan hanya untuk kenyamanan
        Anda dan Anda mengakses dan menggunakannya sepenuhnya dengan risiko Anda
        sendiri dan tunduk pada syarat dan ketentuan pihak ketiga tersebut.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 10px !important;
          margin-bottom: 0 !important;
        "
      >
        Teknologi Pelacakan
      </h4>
      <b>Cookies</b>
      <p>
        Kami menggunakan Cookies untuk meningkatkan kinerja dan fungsionalitas
        situs web kami tetapi tidak penting untuk penggunaannya. Namun, tanpa
        cookie ini, fungsionalitas tertentu mungkin tidak tersedia.
      </p>
      <b>Local Storage</b>
      <p>
        Penyimpanan Lokal terkadang dikenal sebagai penyimpanan DOM, menyediakan
        aplikasi web dengan metode dan protokol untuk menyimpan data sisi klien.
        Penyimpanan web mendukung penyimpanan data yang persisten, mirip dengan
        cookie tetapi dengan kapasitas yang sangat ditingkatkan dan tidak ada
        informasi yang disimpan di header requirements HTTP.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 10px !important;
          margin-bottom: 0 !important;
        "
      >
        Informasi tentang General Data Protection Regulation (GDPR)
      </h4>
      <p>
        Kami mungkin mengumpulkan dan menggunakan informasi dari Anda jika Anda
        berasal dari Wilayah Ekonomi Eropa (European Economic Area / EEA), dan
        di bagian Kebijakan Privasi ini kami akan menjelaskan dengan tepat
        bagaimana dan mengapa data ini dikumpulkan, dan bagaimana kami menyimpan
        data ini di bawah perlindungan agar tidak direplikasi atau digunakan
        dengan cara yang salah.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 10px !important;
          margin-bottom: 0 !important;
        "
      >
        Apakah GDPR?
      </h4>
      <p>
        GDPR adalah undang-undang privasi dan perlindungan data di seluruh UE
        yang mengatur bagaimana data penduduk UE dilindungi oleh perusahaan dan
        meningkatkan kontrol yang dimiliki penduduk UE atas data pribadi mereka.
      </p>
      <p>
        GDPR adalah undang-undang privasi dan perlindungan data di seluruh UE
        yang mengatur bagaimana data penduduk UE dilindungi oleh perusahaan dan
        meningkatkan kontrol yang dimiliki penduduk UE atas data pribadi mereka.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 10px !important;
          margin-bottom: 0 !important;
        "
      >
        Apa itu data pribadi?
      </h4>
      <p>
        Setiap data yang terkait dengan individu yang dapat diidentifikasi atau
        diidentifikasi. GDPR mencakup spektrum informasi yang luas yang dapat
        digunakan sendiri, atau dikombinasikan dengan informasi lain, untuk
        mengidentifikasi seseorang. Data pribadi melampaui nama atau alamat
        email seseorang. Beberapa contoh termasuk informasi keuangan, opini
        politik, data genetik, data biometrik, alamat IP, alamat fisik,
        orientasi seksual, dan etnis.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 10px !important;
          margin-bottom: 0 !important;
        "
      >
        Prinsip Perlindungan Data mencakup persyaratan seperti:
      </h4>
      <ul>
        <li>
          Data pribadi yang dikumpulkan harus diproses dengan cara yang adil,
          legal, dan transparan dan hanya boleh digunakan dengan cara yang
          diharapkan secara wajar.
        </li>
        <li>
          Data pribadi hanya boleh dikumpulkan untuk memenuhi tujuan tertentu
          dan hanya boleh digunakan untuk tujuan itu. Organisasi harus
          menentukan mengapa mereka membutuhkan data pribadi saat
          mengumpulkannya.
        </li>
        <li>
          Data pribadi harus disimpan tidak lebih dari yang diperlukan untuk
          memenuhi tujuannya.
        </li>
        <li>
          Orang-orang yang tercakup dalam GDPR memiliki hak untuk mengakses data
          pribadi mereka sendiri. Mereka juga dapat meminta salinan datanya, dan
          agar datanya diperbarui, dihapus, dibatasi, atau dipindahkan ke
          organisasi lain.
        </li>
      </ul>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 10px !important;
          margin-bottom: 0 !important;
        "
      >
        Mengapa GDPR penting?
      </h4>
      <p>
        GDPR menambahkan beberapa persyaratan baru terkait bagaimana perusahaan
        harus melindungi data pribadi individu yang mereka kumpulkan dan proses.
        Hal ini juga meningkatkan taruhan untuk kepatuhan dengan meningkatkan
        penegakan hukum dan memberlakukan denda yang lebih besar untuk
        pelanggaran. Di luar fakta-fakta ini, ini hanyalah hal yang benar untuk
        dilakukan. Di Help Scout, kami sangat yakin bahwa privasi data Anda
        sangat penting dan kami telah menerapkan praktik keamanan dan privasi
        yang solid yang melampaui persyaratan peraturan baru ini.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 10px !important;
          margin-bottom: 0 !important;
        "
      >
        Hak Subjek Data Individu - Akses, Portabilitas, dan Penghapusan Data
      </h4>
      <p>
        Hak Subjek Data Individu - Akses, Portabilitas, dan Penghapusan Data
        Kami berkomitmen untuk membantu pelanggan kami memenuhi persyaratan hak
        subjek data GDPR. Proses VHP Self Check-in atau menyimpan semua data
        pribadi di vendor yang sepenuhnya sesuai dengan DPA. Kami menyimpan
        semua percakapan dan data pribadi hingga 6 tahun kecuali akun Anda
        dihapus. Dalam hal ini, kami membuang semua data sesuai dengan
        Persyaratan Layanan dan Kebijakan Privasi kami, tetapi kami tidak akan
        menyimpannya lebih dari 60 hari.
      </p>
      <p>
        Kami menyadari bahwa jika Anda bekerja dengan pelanggan UE, Anda harus
        dapat memberi mereka kemampuan untuk mengakses, memperbarui, mengambil,
        dan menghapus data pribadi. Kami punya kamu! Kami telah disiapkan
        sebagai layanan mandiri sejak awal dan selalu memberi Anda akses ke data
        Anda dan data pelanggan Anda. Tim dukungan pelanggan kami siap membantu
        Anda menjawab pertanyaan apa pun yang mungkin Anda miliki tentang
        bekerja dengan API.
      </p>
      <h4
        style="
          font-size: 18px !important;
          margin-top: 10px !important;
          margin-bottom: 0 !important;
        "
      >
        Hubungi Kami
      </h4>
      <p>Jangan ragu untuk menghubungi kami jika Anda memiliki pertanyaan.</p>
      <ul>
        <li>Email: <a href="mailto:info@sindata.net">info@sindata.net</a></li>
        <li>Telepon: (62) 21 - 50860678</li>
        <li>
          Website:
          <a href="https://www.sindata.net">https://www.sindata.net</a>
        </li>
        <li>
          Alamat: Jl. Bukit Gading Raya, Gading Bukit Indah Blok O No. 3-5,
          Jakarta 14240 - Indonesia
        </li>
      </ul>
    </div>`,
    },
  ],
};
